site_name: ğŸ€@lyx
site_description: åœ¨çº¿äº‘æ–‡æ¡£
site_author: lyx
copyright: Copyright &copy; 2022 - 2099 @lyx
site_url: https://mkdocs.lyx2099.top/
repo_url: https://github.com/lyx2099/mkdocs
repo_name: mkdocs
edit_uri: ""

# ä¸»é¢˜é…ç½®
theme:
  name: material
  language: en
  search_index_only: true
  # è°ƒè‰²æ¿
  palette:
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   toggle:
    #     icon: material/brightness-7
    #     name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   primary: red    # è®¾ç½®å¯¼èˆªæ¡çš„é¢œè‰²
    #   scheme: slate
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
        # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
        
  features:
    #- navigation.instant # ç‚¹å‡»å†…éƒ¨é“¾æ¥æ—¶ï¼Œä¸ç”¨å…¨éƒ¨åˆ·æ–°é¡µé¢
    - navigation.tracking # åœ¨urlä¸­ä½¿ç”¨æ ‡é¢˜å®šä½é”šç‚¹
    - navigation.tabs # é¡¶éƒ¨æ˜¾ç¤ºå¯¼èˆªé¡¶å±‚navï¼ˆä¹Ÿå°±æ˜¯ç¬¬ä¸€ä¸ªèŠ‚ç‚¹ï¼‰
    - navigation.tabs.sticky # æ»šåŠ¨æ˜¯éšè—é¡¶éƒ¨navï¼Œéœ€è¦é…åˆnavigation.tabsä½¿ç”¨
    - navigation.sections # navèŠ‚ç‚¹ç¼©è¿›
    - navigation.expand # ä¸æŠ˜å å·¦ä¾§navèŠ‚ç‚¹
    - navigation.indexes # æŒ‡å®šèŠ‚ç‚¹index pages ï¼Œè·Ÿinstantä¸å…¼å®¹
    - toc.integrate # å³ä¾§ç”Ÿäº§ç›®å½•
    - toc.integrate #å¯¼èˆªé›†æˆ
    - navigation.top # ä¸€é”®å›é¡¶éƒ¨
    - header.autohide
    - search.share # æœç´¢åˆ†äº«
    - search.suggest # æœç´¢å»ºè®®
    - search.highlight #æœç´¢é«˜äº®

plugins:
  - search:
      jieba_dict: user_dict.txt

# å›¾æ ‡
icon:
  admonition:
    note: octicons/tag-16
    abstract: octicons/checklist-16
    info: octicons/info-16
    tip: octicons/squirrel-16
    success: octicons/check-16
    question: octicons/question-16
    warning: octicons/alert-16
    failure: octicons/x-circle-16
    danger: octicons/zap-16
    bug: octicons/bug-16
    example: octicons/beaker-16
    quote: octicons/quote-16

# æ‰©å±•
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - def_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.caret #ä¸‹åˆ’çº¿
  - pymdownx.mark #æ–‡æœ¬é«˜äº®
  - pymdownx.tilde #åˆ é™¤çº¿

# è‡ªå®šä¹‰css
extra_css:
  - "//cdn.staticaly.com/gh/codeslive/cdn@main/css/imageszoom.css" #å›¾ç‰‡æ”¾å¤§css
  #- '//cdn.staticaly.com/gh/codeslive/images-pages@main/cdn/css/custom.css'
  #- '//cdn.staticaly.com/gh/codeslive/images-pages@main/cdn/css/simplelightbox.min.css' #å›¾ç‰‡æ”¾å¤§css

# è‡ªå®šä¹‰js
extra_javascript:
  - "//cdn.staticaly.com/gh/codeslive/cdn@main/js/busuanzi.pure.mini.js" # ç½‘ç«™è®¿é—®ç»Ÿè®¡
  - "//cdn.staticaly.com/gh/codeslive/cdn@main/js/imageszoom.js" # å›¾ç‰‡æ”¾å¤§js
  #- '//cdn.staticaly.com/gh/codeslive/cdn@main/js/jquery-3.2.1.min.js'
  #- '//cdn.staticaly.com/gh/codeslive/cdn@main/js/simplelightbox.min.js'  #å›¾ç‰‡æ”¾å¤§js
  #- '//cdn.staticaly.com/gh/codeslive/cdn@main/js/custom.js'

# è®¾ç½®
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lyx2099
      name: github
    - icon: fontawesome/brands/slack
      link: https://lyx2099.github.io
      name: myblog
    - icon: fontawesome/solid/paper-plane
      link: mailto:leeyx0913@foxmail.com
      name: é‚®ç®±åœ°å€

# æ–‡æ¡£åŒº
nav:
  - æ–‡æ¡£ä»‹ç»: "index.md"
  - "åœ¨çº¿äº‘æ–‡æ¡£":
      - "é™æ€äº‘æ–‡æ¡£":
          - mkdoc: "index.md"
          - docsify: "index.md"
      - "åŠ¨æ€äº‘æ–‡æ¡£":
          - leanote: "index.md"
          - mrdoc: "index.md"
          - showdoc: "index.md"
  - ä¸ªäººåšå®¢æ­å»º:
      - "é™æ€åšå®¢":
          - hexo: "index.md"
          - vuepress: "index.md"
      - "åŠ¨æ€åšå®¢":
          - halo: "index.md"
          - worldpress: "index.md"
  - å¼€å‘è®°å½•: "index.md"
